"""add_extras_arg_to_openai

Revision ID: f6d7b8ea651b
Revises: 149ba34714a9
Create Date: 2023-07-27 17:47:48.722050

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f6d7b8ea651b"
down_revision = "149ba34714a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("openai_requests", sa.Column("extras", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("openai_requests", "extras")
    # ### end Alembic commands ###
