---
name: 'Guardrails'

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  stale:
    name: Check Guardrails
    uses: wealthsimple/github-workflows/.github/workflows/guardrails.yml@v1
    secrets: inherit
